server:
  port: 7001
  max-http-header-size: 40960
spring:
  # 应用名
  application:
    name: chart-service
  datasource:
    name: mysqlDataSource
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE_NAME:learn_dev}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME:dev}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.jdbc.Driver

# 日志配置
logging:
  config: classpath:log4j2.yml

# 配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://xiaoliu:admin@localhost:8606/eureka/
# Mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 控制swagger-ui的显示隐藏：true->显示，false->隐藏
swagger:
  show: true