server:
  port: 7001
  max-http-header-size: 40960
spring:
  # 应用名
  application:
    name: auth-service
  datasource:
    #    name: mysqlDataSource
    #    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE_NAME:learn_dev}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    #    username: ${MYSQL_USERNAME:dev}
    #    password: ${MYSQL_PASSWORD:123456}
    #    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: mergeStat,wall,logback
      initial-size: 5
      max-active: 50
      min-idle: 5
      max-wait: 6000
      validation-query: SELECT 'x'
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
        # 数据源1 业务数据
      datasource1:
        url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE_NAME:learn_dev}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:root}
        driverClassName: com.mysql.jdbc.Driver
      # shiro数据源，用于权限相关
      shiro-datasource:
        url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE_NAME:learn_dev}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_PASSWORD:root}
        driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1

global-config-shiro:
  # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  idType: 3
  # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
  fieldStrategy: 2
  # 驼峰下划线转换
  dbColumnUnderline: true
  # 刷新mapper 调试神器
  refreshMapper: true

# 日志配置
logging:
  config: classpath:log4j2.yml

# 配置注册中心
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://xiaoliu:admin@localhost:8606/eureka/
# Mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 控制swagger-ui的显示隐藏：true->显示，false->隐藏
swagger:
  show: true
#swagger:
#  title: 权限服务
#  description: 权限中心
#  version: 1.0.RELEASE
#  license: Apache License, Version 2.0
#  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
#  terms-of-service-url: https://github.com/fubiaoLiu/spring-cloud-learn/tree/master/sc-services/auth-service
#  base-package: com.example
#  base-path: /**
#  exclude-path: /error, /ops/**