server:
  port: 8605
spring:
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://xiaoliu:admin@localhost:8606/eureka/
zuul:
  # 禁止服务名路由
  ignored-services: "*"
  # 路由前缀
  prefix: /api
  # 路由后是否跳过前缀，默认就是true，表示路由后的地址不包含前缀
  strip-prefix: true
  # 配置路由
  routes:
    chart-service:
      path: /chart/**
    config-client-service:
      path: /config/**
    kafka-producer-service:
      path: /kafka/producer/**
    kafka-consumer-service:
      path: /kafka/consumer/**
    rocketmq-producer-service:
      path: /rocketmq/producer/**
    rocketmq-consumer-service:
      path: /rocketmq/consumer/**
    sentinel-service:
      path: /sentinel/**
    unit-test-service:
      path: /ut/**
    consumer-service:
      path: /consumer/**
    provider-service:
      path: /provider/**
  # 取消重试机制
  retryable: false
  add-host-header: true
  sensitive-headers:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

# 暴露actuator的所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

# 日志配置
logging:
  config: classpath:log4j2.yml
  level:
    root: warn

# swagger 配置
swagger:
  show: true
#  servlet-path: /
#security:
#  basic:
#    enabled: false
#  oauth2:
#    resource:
#      prefer-token-info: false
