spring:
  profiles:  # 环境切换
    active: dev
  application:
    name: api-gateway

# 日志配置
logging:
  config: classpath:log4j2.yml
  level:
    root: warn
zuul:
  sensitive-headers:
  strip-prefix: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

#  servlet-path: /
#security:
#  basic:
#    enabled: false
#  oauth2:
#    resource:
#      prefer-token-info: false

---
# 开发环境
spring:
  profiles: dev
server:
  port: 8605
eureka:
  client:
    serviceUrl:
      defaultZone: http://xiaoliu:admin@localhost:8406/eureka/

zuul:
  routes:
    chart-service:
      path: /chart/**
    config-client-service:
      path: /config/**
    kafka-producer-service:
      path: /kafka/producer/**
    kafka-consumer-service:
      path: /kafka/consumer/**
    rocketmq-producer-service:
      path: /rocketmq/producer/**
    rocketmq-consumer-service:
      path: /rocketmq/consumer/**
    sentinel-service:
      path: /sentinel/**
    unit-test-service:
      path: /ut/**
  # 取消重试机制
  retryable: false
  add-host-header: true
logging:
  path: /var/log/sc-modules
  file: ${spring.application.name}.log
  level: debug

# swagger 配置
swagger:
  show: true


---

# 测试环境
spring:
  profiles: test
server:
  port: 8605
eureka:
  client:
    serviceUrl:
      defaultZone: http://xiaoliu:admin@127.0.0.1:8606/eureka/
zuul:
  routes:
    chart-service:
      path: /chart/**
    rocketmq-service:
      path: /rocketmq/**
  # 取消重试机制
  retryable: false
  add-host-header: true
# swagger 配置
swagger:
  show: true
