spring:
# 应用名
  application:
    name: consumer-service
# 环境切换
  profiles:
    active: dev
# 连接池配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化时建立物理连接的个数
      initialSize: 3
      # 最小连接池数量
      minIdle: 3
      # 最大连接池数量
      maxActive: 20
      # 获取连接等待超时的时间
      maxWait: 60000
      # 连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validationQuery: SELECT 1
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testWhileIdle: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计。监控统计用的filter:stat; 日志用的filter:log4j; 防御sql注入的filter:wall
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # 排除一些静态资源，以提高效率
      web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # druid连接池监控用户名/密码
      stat-view-servlet:
        login-username: admin
        login-password: 123456

# 日志配置
logging:
  config: classpath:log4j2.yml

# spring security 基础认证关闭
#security:
#  basic:
#    enabled: false

# RocketMQ消费者
rocketmq:
  consumer:
    # Consumer组名，多个Consumer如果属于一个应用，订阅同样的消息，且消费逻辑一致，则应该将它们归为同一组。默认DEFAULT_CONSUMER
    consumerGroup: ${spring.application.name}
    # namesrv地址
    namesrvAddr: 192.168.101.216:9876;192.168.101.217:9876;192.168.101.218:9876
    # 消费线程池最大线程数。默认10
    consumeThreadMin: 10
    # 消费线程池最大线程数。默认20
    consumeThreadMax: 20
    # 批量消费，一次消费多少条消息。默认1
    consumeMessageBatchMaxSize: 1
    # 批量拉消息，一次最多拉多少条。默认32
    pullBatchSize: 32
    # 订阅的主题和tags("*"号表示订阅该主题下所有的tags),格式：topic~tag1||tag2||tag3;topic2~*
    # topics: DemoTopic~*
    topics: user-topic

---
# 开发环境
server:
  port: 7003
  max-http-header-size: 40960
spring:
  profiles: dev
  datasource:
      name: mysqlDataSource
        url: jdbc:mysql://192.168.101.1:3306/learn_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      driver-class-name: com.mysql.jdbc.Driver
 #配置注册中心
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://xiaoliu:admin@localhost:8606/eureka/
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 控制swagger-ui的显示隐藏：true->显示，false->隐藏
swagger:
 show: true
---
# 测试环境
server:
  port: 7003
  max-http-header-size: 40960
spring:
  profiles: test
  datasource:
      name: mysqlDataSource
      url: jdbc:mysql://192.168.101.1:3306/learn_test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
      username: test
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver

     #配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://xiaoliu:admin@localhost:8606/eureka/
#mybatis的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 控制swagger-ui的显示隐藏：true->显示，false->隐藏
swagger:
 show: true
